language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  webhooks:
    urls:
      - $GITTER_ROOM_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
node_js:
  - '11.6.0'
  - '10'
  - '8'
after_success:
  - npm run travis:deploy-once "npm run semantic-release"
  - npm run travis:deploy-once "gulp docs:publish"
  - npm run travis:deploy-once "gulp examples:publish"
  - npm run travis:coveralls
branches:
  except:
    - /^v\d+\.\d+\.\d+$/

